*** Starting uWSGI 2.0.21 (64bit) on [Tue Oct 31 23:22:06 2023] ***
compiled with version: 11.2.0 on 10 March 2023 16:42:24
os: Linux-5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
nodename: workspace
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/workspace/Data/My_Git/web_met/server_met
writing pidfile to uwsgi.pid
detected binary path: /home/workspace/anaconda3/envs/met_dev/bin/uwsgi
chdir() to /home/workspace/Data/My_Git/web_met/server_met/
your processes number limit is 63131
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9001 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:37319 (port auto-assigned) fd 3
Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x19d47c0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x19d47c0 pid: 222426 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 222426)
spawned uWSGI worker 1 (pid: 222427, cores: 1)
spawned uWSGI worker 2 (pid: 222428, cores: 1)
spawned uWSGI worker 3 (pid: 222429, cores: 1)
spawned uWSGI worker 4 (pid: 222430, cores: 1)
spawned uWSGI http 1 (pid: 222431)
测试 auto now 0 9
31/Oct/2023:23:22:17 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_data | request_body_size:174 | response_body_size:950378
31/Oct/2023:23:22:23 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:84 | response_body_size:4362487
31/Oct/2023:23:22:26 +0800 | pid:222429 wid:3 | HTTP/1.1 200 | GET | 172.21.158.40:9001/admindjango_apscheduler/djangojobexecution/ | request_body_size:0 | response_body_size:64684
31/Oct/2023:23:22:30 +0800 | pid:222429 wid:3 | HTTP/1.1 404 | GET | 172.21.158.40:9001/static/admin/js/vendor/jquery/jquery.min.js | request_body_size:0 | response_body_size:179
31/Oct/2023:23:22:30 +0800 | pid:222429 wid:3 | HTTP/1.1 200 | GET | 172.21.158.40:9001/adminjsi18n/ | request_body_size:0 | response_body_size:8398
31/Oct/2023:23:22:30 +0800 | pid:222430 wid:4 | HTTP/1.1 404 | GET | 172.21.158.40:9001/static/admin/js/vendor/xregexp/xregexp.min.js | request_body_size:0 | response_body_size:179
31/Oct/2023:23:22:30 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | GET | 172.21.158.40:9001/admin | request_body_size:0 | response_body_size:13319
31/Oct/2023:23:22:32 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | GET | 172.21.158.40:9001/admindjango_apscheduler/djangojobexecution/ | request_body_size:0 | response_body_size:64684
31/Oct/2023:23:22:33 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | GET | 172.21.158.40:9001/adminjsi18n/ | request_body_size:0 | response_body_size:8398
31/Oct/2023:23:22:33 +0800 | pid:222429 wid:3 | HTTP/1.1 404 | GET | 172.21.158.40:9001/static/admin/js/vendor/jquery/jquery.min.js | request_body_size:0 | response_body_size:179
31/Oct/2023:23:22:33 +0800 | pid:222430 wid:4 | HTTP/1.1 404 | GET | 172.21.158.40:9001/static/admin/js/vendor/xregexp/xregexp.min.js | request_body_size:0 | response_body_size:179
31/Oct/2023:23:22:38 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:84 | response_body_size:4362487
31/Oct/2023:23:22:53 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:84 | response_body_size:4362487
31/Oct/2023:23:23:11 +0800 | pid:222430 wid:4 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:84 | response_body_size:4362487
SIGINT/SIGTERM received...killing workers...
!!! uWSGI process 222430 got Segmentation Fault !!!
!!! uWSGI process 222429 got Segmentation Fault !!!
*** backtrace of 222430 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4b40642520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f4b406453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f4b40645610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4b40642520]
/lib/x86_64-linux-gnu/libc.so.6(+0x91117) [0x7f4b40691117]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7f4b40693a41]
/home/workspace/anaconda3/envs/met_dev/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so(_Z9th_workerPv+0x378) [0x7f4afedcad18]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f4b40694ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f4b40726a40]
*** end of backtrace ***
*** backtrace of 222429 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4b40642520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f4b406453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f4b40645610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4b40642520]
/lib/x86_64-linux-gnu/libc.so.6(epoll_wait+0x5e) [0x7f4b4072601e]
uwsgi(event_queue_wait+0x36) [0x64a3c6]
uwsgi(wsgi_req_accept+0x130) [0x605bb0]
uwsgi(simple_loop_run+0xc1) [0x6532e1]
uwsgi(simple_loop+0x11) [0x6530c1]
uwsgi(uwsgi_ignition+0x315) [0x658135]
uwsgi(uwsgi_worker_run+0x1dd) [0x65cc0d]
uwsgi(uwsgi_run+0x4d1) [0x65d2f1]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f4b40629d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f4b40629e40]
uwsgi() [0x604f6e]
*** end of backtrace ***
gateway "uWSGI http 1" has been buried (pid: 222431)
worker 1 buried after 0 seconds
worker 2 buried after 0 seconds
worker 3 buried after 0 seconds
worker 4 buried after 0 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.21 (64bit) on [Mon Nov 13 14:47:26 2023] ***
compiled with version: 11.2.0 on 10 March 2023 16:42:24
os: Linux-5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
nodename: workspace
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/workspace/Data/My_Git/web_met/server_met
writing pidfile to uwsgi.pid
detected binary path: /home/workspace/anaconda3/envs/met_dev/bin/uwsgi
chdir() to /home/workspace/Data/My_Git/web_met/server_met/
your processes number limit is 63131
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9001 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33539 (port auto-assigned) fd 3
Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15e37c0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 656280 bytes (640 KB) for 8 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x15e37c0 pid: 361044 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 361044)
spawned uWSGI worker 1 (pid: 361048, cores: 1)
spawned uWSGI worker 2 (pid: 361049, cores: 1)
spawned uWSGI worker 3 (pid: 361050, cores: 1)
spawned uWSGI worker 4 (pid: 361051, cores: 1)
spawned uWSGI worker 5 (pid: 361052, cores: 1)
spawned uWSGI worker 6 (pid: 361053, cores: 1)
spawned uWSGI worker 7 (pid: 361054, cores: 1)
spawned uWSGI worker 8 (pid: 361055, cores: 1)
spawned uWSGI http 1 (pid: 361056)
13/Nov/2023:14:47:38 +0800 | pid:361055 wid:8 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:26 | response_body_size:26710
/home/workspace/Data/My_Git/web_met/server_met/./zdz/common/utils/data_class.py:1989: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(rsql, con=self.conn)
/home/workspace/Data/My_Git/web_met/server_met/./zdz/common/utils/data_class.py:2129: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rain_tz['rank']=pd.cut(rain_tz['PRE'],bins,right=False,labels=labels)
13/Nov/2023:14:47:55 +0800 | pid:361055 wid:8 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_data | request_body_size:100 | response_body_size:113986
/home/workspace/Data/My_Git/web_met/server_met/./zdz/common/utils/data_class.py:1989: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(rsql, con=self.conn)
13/Nov/2023:14:48:02 +0800 | pid:361048 wid:1 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_data | request_body_size:108 | response_body_size:666109
13/Nov/2023:14:48:08 +0800 | pid:361049 wid:2 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:26 | response_body_size:26710
/home/workspace/Data/My_Git/web_met/server_met/./zdz/common/utils/data_class.py:498: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remain.sort_values(by="value",axis=0,ascending=ascending_list[value_index],inplace=True) # 从大到小
13/Nov/2023:14:48:17 +0800 | pid:361050 wid:3 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_data | request_body_size:178 | response_body_size:938426
/home/workspace/Data/My_Git/web_met/server_met/./zdz/common/utils/data_class.py:498: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remain.sort_values(by="value",axis=0,ascending=ascending_list[value_index],inplace=True) # 从大到小
13/Nov/2023:14:48:34 +0800 | pid:361053 wid:6 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_data | request_body_size:178 | response_body_size:2408828
13/Nov/2023:14:48:38 +0800 | pid:361053 wid:6 | HTTP/1.1 200 | POST | 172.21.158.40:9001/station_zdz_warring | request_body_size:26 | response_body_size:33871
SIGINT/SIGTERM received...killing workers...
!!! uWSGI process 361053 got Segmentation Fault !!!
!!! uWSGI process 361050 got Segmentation Fault !!!
!!! uWSGI process 361055 got Segmentation Fault !!!
!!! uWSGI process 361049 got Segmentation Fault !!!
!!! uWSGI process 361048 got Segmentation Fault !!!
*** backtrace of 361050 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f7f8ca453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f7f8ca45610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x91117) [0x7f7f8ca91117]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7f7f8ca93a41]
/home/workspace/anaconda3/envs/met_dev/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so(_Z9th_workerPv+0x378) [0x7f7f4b22bd18]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f7f8ca94ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f7f8cb26a40]
*** end of backtrace ***
*** backtrace of 361055 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f7f8ca453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f7f8ca45610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x91117) [0x7f7f8ca91117]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7f7f8ca93a41]
/home/workspace/anaconda3/envs/met_dev/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so(_Z9th_workerPv+0x378) [0x7f7f4b22bd18]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f7f8ca94ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f7f8cb26a40]
*** end of backtrace ***
*** backtrace of 361053 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f7f8ca453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f7f8ca45610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x91117) [0x7f7f8ca91117]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7f7f8ca93a41]
/home/workspace/anaconda3/envs/met_dev/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so(_Z9th_workerPv+0x378) [0x7f7f4b22bd18]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f7f8ca94ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f7f8cb26a40]
*** end of backtrace ***
*** backtrace of 361048 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f7f8ca453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f7f8ca45610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x91117) [0x7f7f8ca91117]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7f7f8ca93a41]
/home/workspace/anaconda3/envs/met_dev/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so(_Z9th_workerPv+0x378) [0x7f7f4b22bd18]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f7f8ca94ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f7f8cb26a40]
*** end of backtrace ***
*** backtrace of 361049 ***
uwsgi(uwsgi_backtrace+0x31) [0x6578e1]
uwsgi(uwsgi_segfault+0x32) [0x657d52]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x453fc) [0x7f7f8ca453fc]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f7f8ca45610]
uwsgi() [0x608577]
uwsgi(end_me+0x31) [0x654451]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7f8ca42520]
/lib/x86_64-linux-gnu/libc.so.6(+0x91117) [0x7f7f8ca91117]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7f7f8ca93a41]
/home/workspace/anaconda3/envs/met_dev/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so(_Z9th_workerPv+0x378) [0x7f7f4b22bd18]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f7f8ca94ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f7f8cb26a40]
*** end of backtrace ***
gateway "uWSGI http 1" has been buried (pid: 361056)
worker 1 buried after 0 seconds
worker 2 buried after 0 seconds
worker 3 buried after 0 seconds
worker 4 buried after 0 seconds
worker 5 buried after 0 seconds
worker 6 buried after 0 seconds
worker 7 buried after 0 seconds
worker 8 buried after 0 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
